<?xml version="1.0" encoding="utf-8"?>
<Database Name="Frog" Class="CourseListDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Frog.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Conn_Str_Forg" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CourseList" Member="CourseLists">
    <Type Name="CourseList">
      <Column Name="EmployeeCourseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CodeCourse" Type="System.String" DbType="NVarChar(207)" CanBeNull="true" />
      <Column Name="isPass" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>